version: "3.5"

services:
  dbmysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=rinha
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin", "-uuser", "-ppassword", "ping", "-h", "localhost"]
            timeout: 15s
            retries: 3

  nginx:
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - 9999:9999

  app1: &app1
    image: rinha
    hostname: app1
    restart: on-failure
    depends_on:
      dbmysql:
        condition: service_healthy
    environment:
      - PORT=5001
      - DB_HOST=dbmysql
      - DB_NAME=rinha
      - DB_USER=user
      - DB_PASS=password
    entrypoint: ./startup-migrations.sh
    
  app2:
    <<: *app1
    hostname: app2
    environment:
      - PORT=5002
      - DB_HOST=dbmysql
      - DB_NAME=rinha
      - DB_USER=user
      - DB_PASS=password

volumes:
  my-db:


