version: "3.5"

services:
  db-mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=rinha
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  nginx:
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - application1
      - application2
    ports:
      - 9999:9999

  application1: &application1
    image: rinha
    hostname: application1
    restart: on-failure
    depends_on:
      db-mysql:
        condition: service_healthy
    environment:
      - PORT=5001
      - DB_HOST=db-mysql
      - DB_NAME=rinha
      - DB_USER=user
      - DB_PASS=password
    entrypoint: ./startup-migrations.sh
    
  application2:
    <<: *application1
    hostname: application2
    environment:
      - PORT=5002
      - DB_HOST=db-mysql
      - DB_NAME=rinha
      - DB_USER=user
      - DB_PASS=password

volumes:
  my-db:


