version: "3.5"

services:
  application1: &application1
    image: wlad-rinha
    hostname: application1
    network_mode: host
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://user:pass@mongodb/Rinha?authSource=admin
      - PORT=5000
    
  application2:
    <<: *application1
    hostname: application2
    environment:
      - MONGO_URI=mongodb://user:pass@mongodb/Rinha?authSource=admin
      - PORT=5001

  nginx:
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - application1
      - application2
    network_mode: host
    
  mongodb:
    image: mongo
    hostname: mongodb
    network_mode: host
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
