FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm install -g sequelize-cli

RUN chmod 755 startup-migrations.sh

EXPOSE ${PORT}

CMD ["sh", "-c","--","echo 'started';while true; do sleep 1000; done"]
